const wordSeeds = [
  ["hello", "ciao"], ["goodbye", "arrivederci"], ["please", "per favore"], ["thank you", "grazie"],
  ["yes", "sì"], ["no", "no"], ["friend", "amico"], ["family", "famiglia"],
  ["house", "casa"], ["water", "acqua"], ["food", "cibo"], ["bread", "pane"],
  ["coffee", "caffè"], ["book", "libro"], ["school", "scuola"], ["work", "lavoro"],
  ["day", "giorno"], ["night", "notte"], ["morning", "mattina"], ["beautiful", "bello"],
  ["small", "piccolo"], ["big", "grande"], ["happy", "felice"], ["good", "buono"],
  ["new", "nuovo"], ["old", "vecchio"], ["red", "rosso"], ["blue", "blu"],
  ["green", "verde"], ["one", "uno"], ["two", "due"], ["three", "tre"],
  ["today", "oggi"], ["tomorrow", "domani"], ["where", "dove"], ["when", "quando"],
  ["how", "come"], ["who", "chi"], ["I understand", "capisco"], ["I do not understand", "non capisco"],
  ["I", "io"], ["you", "tu"], ["man", "uomo"], ["woman", "donna"],
  ["child", "bambino"], ["mother", "madre"], ["father", "padre"], ["brother", "fratello"],
  ["sister", "sorella"], ["city", "città"], ["street", "strada"], ["car", "macchina"],
  ["train", "treno"], ["bus", "autobus"], ["airport", "aeroporto"], ["bathroom", "bagno"],
  ["kitchen", "cucina"], ["room", "stanza"], ["table", "tavolo"], ["chair", "sedia"],
  ["door", "porta"], ["window", "finestra"], ["money", "denaro"], ["shop", "negozio"],
  ["market", "mercato"], ["restaurant", "ristorante"], ["hotel", "albergo"], ["ticket", "biglietto"],
  ["doctor", "medico"], ["pharmacy", "farmacia"], ["hospital", "ospedale"], ["clothes", "vestiti"],
  ["shoes", "scarpe"], ["dog", "cane"], ["cat", "gatto"], ["sun", "sole"],
  ["rain", "pioggia"], ["hot", "caldo"], ["cold", "freddo"], ["white", "bianco"],
  ["black", "nero"], ["four", "quattro"], ["five", "cinque"], ["six", "sei"],
  ["seven", "sette"], ["eight", "otto"], ["nine", "nove"], ["ten", "dieci"],
  ["to eat", "mangiare"], ["to drink", "bere"], ["to sleep", "dormire"], ["to speak", "parlare"],
  ["to go", "andare"], ["to come", "venire"], ["to want", "volere"], ["to be able to", "potere"],
  ["to need", "avere bisogno"], ["to live", "vivere"], ["to have", "avere"], ["to be", "essere"]
];

const sentenceSeeds = [
  ["My name is Anna.", "Mi chiamo Anna."],
  ["I am English.", "Sono inglese."],
  ["I live in London.", "Abito a Londra."],
  ["I speak a little Italian.", "Parlo un po' di italiano."],
  ["How are you?", "Come stai?"],
  ["I am very well, thank you.", "Sto molto bene, grazie."],
  ["What is your name?", "Come ti chiami?"],
  ["Where are you from?", "Di dove sei?"],
  ["I would like a coffee, please.", "Vorrei un caffè, per favore."],
  ["The bill, please.", "Il conto, per favore."],
  ["How much does it cost?", "Quanto costa?"],
  ["Where is the bathroom?", "Dov'è il bagno?"],
  ["Where is the station?", "Dov'è la stazione?"],
  ["I need a ticket.", "Ho bisogno di un biglietto."],
  ["What time is it?", "Che ora è?"],
  ["I am looking for a hotel.", "Cerco un albergo."],
  ["I have a reservation.", "Ho una prenotazione."],
  ["Can you help me?", "Puoi aiutarmi?"],
  ["I do not understand.", "Non capisco."],
  ["Please speak slowly.", "Per favore, parla lentamente."],
  ["I am hungry.", "Ho fame."],
  ["I am thirsty.", "Ho sete."],
  ["I would like water.", "Vorrei dell'acqua."],
  ["I like Italian food.", "Mi piace il cibo italiano."],
  ["Today it is sunny.", "Oggi c'è il sole."],
  ["It is cold today.", "Oggi fa freddo."],
  ["See you tomorrow.", "A domani."],
  ["Good morning.", "Buongiorno."],
  ["Good evening.", "Buonasera."],
  ["Excuse me.", "Mi scusi."]
];

export const seedWords = [
  ...wordSeeds.map(([english, italian], index) => ({ id: `seed-${index + 1}`, english, italian, type: "word" })),
  ...sentenceSeeds.map(([english, italian], index) => ({ id: `sentence-${index + 1}`, english, italian, type: "sentence" }))
];
